### PR TITLE
Store return urls in cache along with sessions

### PR DESCRIPTION
**Pull request by jitendrapurohit**
`$response->redirect` for omnipay removes the session vars for anonymous user and redirection to the main page fails from the gateway. This change stores the necessary urls in cache too and retrieves the same if we can't find it in sessions.

https://chat.civicrm.org/civicrm/pl/fr15zp4kdbbt98d8kkwxnft4to

### CODE REVIEW

**Comment by magnolia61** [comment]
wow, I do not understand how, but this PR seems to solve a few issues we had with Mollie.
Using the current master branch with this PR added, Mollie payments work ok, but not only that, also after a failed contribution it does not show a "Thank you, Payment Completed" screen but returns to the payment screen. (so https://github.com/eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor/issues/25 seems to be solved partially by this as well)

**Comment by magnolia61** [comment]
I must mention I succesfully tested against CiviCRM 4.7.18 and nz.co.fuzion.omnipaymultiprocessor 2.1 with this PR applied.

**Comment by eileenmcnaughton** [comment]
There is a security issue here - ie. you could get someone's personal details from a constructed url.

Also, I don't understand why the session doesn't store it. I have the return working based on url retrieval from session on a paymentExpress with Wordpress site. Is this happening with Drupal or? I would have thought we are able to manage sessions with the different CMS so they are not lost when the browser leaves the site?

**Comment by magnolia61** [comment]
Update: this PR helps Mollie for CiviCRM 4.7.18 but doesnt for 4.7.19 or the 4.7.20 nightly.

**Comment by xurizaemon** [comment]
@jitendrapurohit I wonder if your missing session data might be related to something like https://issues.civicrm.org/jira/browse/CRM-20448 ? Try checking the `enableSSL` setting in your local?

**Comment by jitendrapurohit** [comment]
I tried with enabling `Force Secure SSL` on the site which doesn't seem to fix this.

These are the outcome I observed for omnipay payments on Drupal with Paypal PxPay processor.

For logged in user -
 -  contributing via contribution page(works fine).
 -  contribution via webform(works fine).

Form anonymous -
 - contributing via contribution page(works fine).
 - contribution via webform(fails). Session do store the return url before sending it to paypal, but when the $response redirect happens, the variables are lost and we get an empty array for `CRM_Core_Session::singleton()->getVars($sessionVars)` in handlePaymentNotification(). 

Some links which looks similar - https://github.com/barryvdh/laravel-omnipay/issues/1#issuecomment-68174421 mentions to store it in db with trxn_id before redirect to which I followed and made this patch which is working for our site. Not sure what different behavior is followed in this case which doesn't populate the session variables after returning from the paypal site.

**Comment by xurizaemon** [comment]
Ok. Thanks - very much a guess on my part but worth checking i suppose.

It might also be possible that the IPN request from PayPal is making it's request before your browser gets there (but that can only happen if your civi has a public IP address).

I'd observe HTTP requests via server logs during the transaction to see if I saw anything out of order (duplicates or unexpected requests etc).

**Comment by eileenmcnaughton** [comment]
Unfortunately I haven't dug into the webform flow at all :-( Perhaps the session management is different in that case?

**Comment by jitendrapurohit** [comment]
Just found that we need to do a `session_start()` after returning from payment page to populate the previously saved session variables. This seems to happen for all cases except for drupal anonymous user which creates a `lazy_session` and https://github.com/civicrm/civicrm-core/pull/2883/files changes avoid `drupal_session_start()` call for them and resets `$_SESSION` value to empty array.

If I revert that PR, redirect seems to happen correctly for me, but that couldn't be the solution after looking at the impact of it mentioned by Ken on https://forum.civicrm.org/index.php/topic,31800.msg136249.html. Shall I restrict this PR to only apply for the case when `$GLOBALS['lazy_session']` is true? or any other solutions possible ?

**Comment by xurizaemon** [comment]
If `session_start()` hadn't been fired, then the correct fix is likely to be to correctly bootstrap the UF? Otherwise we are doing so partially/incompletely and will run into tricky edge cases. Is this happening in `civicrm/payment` or `[civicrm.root]/extern/ipn.php`?

**Comment by eileenmcnaughton** [comment]
Yep I think @xurizaemon is right - we need to get to the bottom of why the session is not being loaded correctly,

**Comment by jitendrapurohit** [comment]
Ok - so this happen for webform only because we don't create any session for anonymous users when the webform page is being loaded. This gives rise to the following question which seems to be the reason.

1. Why session is stored when webform is loaded for authenticated users -> Because session for logged in gets started when user logs into the site.

2. Why it works in contribution page for anonymous - CiviCRM creates a basic `qfPrivateKey` and `qfSessionKey` for civi pages and this gets stored in drupal session table when drupal footer gets rendered. It calls `drupal_session_commit()` which then stores the required variables into session table.

3. (Requirement for this issue) Why it doesn't work when anonymous load the webform - We only start creating session when Submit button is clicked on the second page and redirection to paypal is being done. At this point we nowhere commit the session into drupal session table. Hence the session is lost after returning.

So, a drupal session needs to be started(an 0 uid row in session table) to get the variables after returning from the payment gateway.

Two solutions possible -

1) Install a module which creates a session row for each visitor on any page load. (Tested with `ip_geoloc` module which works fine for me) OR
2) Update this PR to commit the session into drupal just before redirecting to payment site. Similar to https://gist.github.com/jitendrapurohit/81b61b12e64bbaf629f138dec255176c

**Comment by eileenmcnaughton** [comment]
So, my thinking is the second one is the right track - but could we make a case for that to go in core in the storeSessionObjects function?

**Comment by jitendrapurohit** [comment]
`storeSessionObject()` gets called from different core files which executes on almost all civi pages. Not sure if it can also affect the requirements of https://github.com/civicrm/civicrm-core/pull/2883 at some point as mentioned above ?

core civi changes which works - https://gist.github.com/jitendrapurohit/f60b347abaa8f80bb0cf1e974f7006ec 

As this is required only on storing return urls for webform submission and anonymous users, thinking if updating this PR would be safe as its scope would be limited?

**Comment by eileenmcnaughton** [comment]
We should probably see if @totten has any thoughts. My feeling is that if it makes sense for webform it likely makes sense. Note that the syntax would be something CMS generic like

CRM_Core_Config::getSingleton()->userSystem->storeSesssion();

With the actual code on the Utils_system_Drupal class or similar

**Comment by totten** [comment]
Repeating what I've understood or inferred... 
 1. Drupal has a `lazy_session` feature wherein it defers session-initialization until shutdown. (The shutdown is detected a few ways, eg `ajax_footer()`, `drupal_page_footer()`, `drupal_exit()`, or `redirect_goto()`.) In each of those functions, they invoke `hook_exit()` and  `drupal_session_commit();`)
 2. As part of the payment-processing protocol, Omnipay issues a redirect and short-circuits the page execution. Drupal never gets a chance to run its shutdown procedure.

A few random couple observations:
 * If you read `ajax_footer()`, `drupal_page_footer()`, or `drupal_exit()` -- they seem to have an idiom of calling `hook_exit()` and then `drupal_session_commit()`. Seems like we should also be calling this hook whenever it short-circuits?
 * It's a  little surprising that Drupal duplicates this code across `ajax_footer()`, `drupal_page_footer()`, `drupal_exit()`, and `redirect_goto()`.  Using  `register_shutdown_function()` would remove some SLOC and avoid this current situation. However, I imagine they've got a valid reason.
 * I agree that https://gist.github.com/jitendrapurohit/f60b347abaa8f80bb0cf1e974f7006ec is going in a better direction (although it should be abstracted through UF/CMS, like Eileen mentions). But I feel a little uncomfortable with the idea that  `drupal_session_commit()` calls `session_destroy()` or `session_write_close()`.  Seems like you'd want to be really certain that we're really done writing to the session.
    * Ex: `CRM_Core_Invoke::runItem()` calls `CRM_Core_Session::storeSessionObjects()` and then returns control back to the CMS. But CMS modules might still make session updates after `runItem()`, right?

Would this frame work: make `CRM_Utils_System::civiExit()` obey the same exit-protocol as D7's `drupal_exit()`: https://gist.github.com/totten/f67d8329c8265ee33196886258f17556

**Comment by jitendrapurohit** [comment]
Changes made in [the above patch](https://gist.github.com/totten/f67d8329c8265ee33196886258f17556) seems to be working fine and stores the return urls in session table correctly. It also works without applying `2-omnipay-exit.diff` changes. 
So only changes that we want is to commit into session table when a civiexit() is being done. Can we do a PR against core ?

**Comment by eileenmcnaughton** [comment]
yes, I think a PR against core makes sense.

**Comment by jitendrapurohit** [comment]
@totten @eileenmcnaughton I've raised a PR for the above fix at https://github.com/civicrm/civicrm-core/pull/10501. Closing this for now.

**Comment by jaapjansma** [comment]
We have the same issues as above. We use civi 4.7.23 and this extension version 2.5. I see that the PR to core is not merged (yet) and that this PR is closed as it is a security risk. 
@jitendrapurohit and @magnolia61 how did you fix this?

**Comment by jaapjansma** [comment]
For now I can confirm that @totten patches does fix the problem. So we have applied the patches and are curious when those patches are applied to core and when to this extension.

**Comment by jitendrapurohit** [comment]
The patch only needs to be merged in core and not in the extension. If it has also worked for you - can you comment on https://github.com/civicrm/civicrm-core/pull/10501 to forward the merge process? Thanks.

**Comment by jaapjansma** [comment]
@itendrapurohit I have commented on the core PR.

**Pull request closed without merging**
