### PR TITLE
Support for First Atlantic Commerce Payment Gateway

### PR DESCRIPTION
**Pull request by cloudcogsio**
- Default behaviour of the gateway is as follows:

1. Direct Integration implementation
(https://firstatlanticcommerce.com/resources/integrationguides/)

2. 3DS Authorization is ON by default.

3. PHP must be configured to use secure session cookies

ini_set('session.cookie_secure', 1);
ini_set('session.cookie_samesite', 'None');

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Great! My only issues are around the white space - for php it should have a carriage return at the end   - that's why github shows

image


And for json - the original spacing was right (& is what composer would normally generate)

**Comment by cloudcogsio** [comment]
I'll add the trailing break for the mgd. 

My IDE must have reformatted the json since I only added the new dependency. 

I'll revert and use a plain text editor for it.

**Comment by eileenmcnaughton** [comment]
Yeah IDE formatting is mostly good & occasionally bad

**Comment by eileenmcnaughton** [comment]
Great!

**Pull request merged**
