### PR TITLE
Hide a couple of unused fields, clear some placeholder labels.

### PR DESCRIPTION
**Pull request by xurizaemon**
Doesn't seem like the URLs need to be populated (no issues creating and saving a processor with them blank) so no point in filling them with http://unused.com (currently a page about Pokemon?).

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Does the parent form no longer enforce those urls to be populated?

**Comment by xurizaemon** [comment]
The parent form permitted me to leave them blank when I tested this change.

**Comment by eileenmcnaughton** [comment]
Ok - I'll take your word for it!

**Comment by xurizaemon** [comment]
I'm thinking (separate PR) I might add some processor-specific CSS to hide unused fields.

**Comment by eileenmcnaughton** [comment]
for the extension or core? sounds core?

**Comment by xurizaemon** [comment]
A core fix would be to replicate the behaviour in .mgd so that any field is hidden if label is NULL (that's how things work right now I believe); then Omnipay can set URL_X=null and hide the field.

If it's some processors only (and I only know about certain processors), the fix belongs in the relevant processor.

**Comment by eileenmcnaughton** [comment]
I think I'm with you - so core  hides fields with labels - but maybe not the url ones? & the change in the Mgd is to ensure the metadata is declared correctly for core to do that?

**Comment by xurizaemon** [comment]
AFAICT / from memory

* Core hides *some* fields if .mgd says they are labelled NULL. 
* Some processor config fields seem to be treated differently. 
* Possibly there are some weird specifics with test mode too.

Fixing those would be nice! I'll be sure to let you know if I get a chance to.

**Comment by eileenmcnaughton** [comment]
Ok so to summarise - there are some things that core may or may not do correctly & it would be good to fix them & then implement required changes to the extension :-)

**Pull request merged**
