### PR TITLE
Reimplement population of $entities

### PR DESCRIPTION
**Pull request by bastienho**
Were removed in eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor@50b580e
eileenmcnaughton/nz.co.fuzion.omnipaymultiprocessor#253

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
thanks @bastienho  - I have a feeling I should move / rename that function since it is being used outside the civix context - which is why civix removed it

**Comment by bastienho** [comment]
Feel free to do that!

I fact, I think it's a good approach

**Comment by eileenmcnaughton** [comment]
@bastienho can you check if what I just pushed works? Its from yours but I just put the function on the same class

**Comment by bastienho** [comment]
It seems much more elegant. 

I'll let you know when I'll have tried out this branch

**Comment by bastienho** [comment]
It seems much more elegant. 

I'll let you know when I'll have tried out this branch

**Comment by eileenmcnaughton** [comment]
thanks @bastienho  - I should probably tag a release asap with that fix

**Comment by bastienho** [comment]
Tested and approved

**Comment by eileenmcnaughton** [comment]
ok I guess this can close

**Pull request closed without merging**
