### PR TITLE
Make an effort to use unique transaction IDs.

### PR DESCRIPTION
**Pull request by xurizaemon**
Refs #26

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
My current thinking around this is that I will add (at some point) a civicrm_payment table via this extension & track all payments that way & hold a field within that table to represent the value passed to the payment processor. At that point the return value can be more flexible & I expect to use some sort of template

**Comment by xurizaemon** [comment]
Sounds like a good plan. But not Smarty for the template, ok? :D

I believe we identified a core processor affected by the same - in :bus: currently so can't check - which makes me wonder if there fix needs to go there instead of in an extension?

**Comment by eileenmcnaughton** [comment]
I seek to conquer all & replace core processors :-) 

Your request for smarty is noted...

**Comment by eileenmcnaughton** [comment]
Closing this - I want to go down the path of pre-fixing & if really necessary templating rather than randomising

**Pull request closed without merging**
