### PR TITLE
This is @adixon's work supporting bluepay and beanstream

### PR DESCRIPTION
**Pull request by JoeMurray**
Some of this seems like coding style changes, other parts functional support for bluepay and beanstream. Would be worthwhile consolidating into one place the various payment processor integrations via omnipay.

### CODE REVIEW

**Comment by JoeMurray** [comment]
I'm not really pushing for this to be merged, just wanting to very gently suggest it from an ecosystem management perspective given benefits of having all implementations in one master repo. You'd have to do some work picking and choosing parts to merge from Alan's work from many years ago that he didn't like that much.

**Comment by eileenmcnaughton** [comment]
@JoeMurray @adixon I tried to do the composer part of this but the core package is now using Omnipay 3.x rather than 2.x & bluepay requires 2.x

I did migrate some omnipay packages across & it wasn't a huge job - but you would need to check

**Comment by adixon** [comment]
I'm not convinced this is a good idea. I didn't really understand how recurring contributions using tokens were working or designed to work with omnipay (and still don't), so this code fork does it in a way that worked but I don't think it was really the right way.

There might be a few small bits that are useful, but it's certainly way out of date and not useful to try to merge as one pull request.

My forks of the corresponding omnipay plugins do likely have some useful things, mostly extensions to support recurring payments, i.e. implementing the token-related functions, but I haven't reviewed or used them with omnipay 3.x.

Joe - I'd suggest that if you have a client who wants to use beanstream or bluepay with omnipay, that instead you create a new project for it and just selectively pull what's useful from my code.

**Comment by eileenmcnaughton** [comment]
thanks @adixon I'll close  this based on that & we can  re-visit if it comes up

**Comment by JoeMurray** [comment]
No, we don't have an active client project for this. Happy to leave closed.

**Pull request closed without merging**
